services:
  postgres:
    image: postgres:18
    container_name: dropthing-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dropthing
      POSTGRES_DB: dropthing
    ports:
      - '6543:5432'
    volumes:
      - pgdata:/var/lib/postgresql/18/data

volumes:
  pgdata:
